background_b: 255
background_g: 86
background_r: 150
rosdistro: 'melodic

  '
roslaunch:
  uris: {host_ubuntu__40429: 'http://ubuntu:40429/'}
rosversion: '1.14.3

  '
run_id: cd9c450a-09e2-11ea-87be-000c2921e801
